---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-operator

---

apiVersion: v1
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flink-operator
rules:
- apiGroups:
  - flink-operator
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - deployments
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - flink.io
  resources:
  - flinkdeployments
  - flinkdeployments/status
  verbs:
  - "*"
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - "*"

---

apiVersion: v1
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flink-operator-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: flink-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: flink-operator
  apiGroup: rbac.authorization.k8s.io
