apiVersion: flink.io/v1alpha1
kind: FlinkApplication
metadata:
  namespace: default
  name: flink-example-statemachine
spec:
  imageName: flink:latest
  jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
  parallelism: 1
  jobManagerResource:
    mem: 2048m
    cpu: 1
  taskManagerResource:
    mem: 2048m
    cpu: 1
  savepointsDir: file:///tmp/savepoints
  savepointGeneration: 0
  flinkConfig:
    taskmanager.numberOfTaskSlots: 2
    kubernetes.jobmanager.service-account: flink-operator
    kubernetes.container-start-command-template: "%java% %classpath% %jvmmem% %jvmopts% %logging% %class% %args%"
